
[build]
target = "aarch64-unknown-linux-gnu"

#[target.aarch64-unknown-linux-gnu]
#linker = "/home/kimtinh/Data/Softwares/gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc"